QUESTIONS = [


  ### Frage Katalog 1 ###  
    # "Was sind die fünf Sicherheitsregeln?",
    # "Welche Berührungsspannungen sind für Menschen zulässig?",
    # "Welche Bedeutung haben die Buchstaben T, N und C in der Kennzeichnung TN-C-System?",
    # "Wie werden bei einem analogen Messgerät der absolute und der relative Fehler berechnet?",
    # "Welche Größen gehen in die Berechnung des Fehlers eines Digitalmessgeräts ein und wie lautet die Formel?",
    # "Was ist ein Kurzschluss?",
    # "Zu welchen Tageszeiten treten laut Tagesbelastungskurve Schwachlast, Mittagsspitze und Feierabendspitze auf?",
    # "Welche Eigenschaften besitzen Grundlastkraftwerke?",
    # "Welche zwei Dioden werden im Rauchmelder oder Brandmelder verwendet?",
    # "Aus welchen drei Widerständen setzt sich der Körperwiderstand R_K zusammen?",
    # "Welche Einflussgrößen wirken sich auf die Strombelastbarkeit von Kabeln und Leitungen aus?",
    # "Was ist die Schleifenimpedanz?",
    # "Aus welchen Bestandteilen bestehen der äußere und der innere Blitzschutz?",
    # "Welche vier Arten von Messfehlern werden im Skript genannt?",
    # "Worin unterscheiden sich Kurzschluss, Leiterschluss, Körperschluss und Erdschluss?",
    # "Ein analoges Messgerät hat die Genauigkeitsklasse 1,5 und einen Messbereichsendwert von 10 V. Wie groß ist der maximal zulässige absolute Fehler?",
    # "Was passiert mit der zulässigen Abschaltzeit im TN-System, wenn die Nennwechselspannung größer wird?",
    # "Wofür steht das X in der Kennzeichnung H05RR-F 3 × 1,5?",
    # "Welche Stromart ist für den Betrieb einer Synchronmaschine vorteilhafter: einphasiger Wechselstrom oder Drehstrom?",
    # "Ist der Anzeigefehler eines Feinmessgeräts größer als der eines Betriebsmessgeräts?",

    # "Was ist ein Kutzschluss?",
    # "Welche Faktoren beinflusen die Strombelastbarkit von Kabeln und Leitungen?",
    # "Nene die fünf Sicherheitsregln in der richtigen Reihenfolge.",
    # "Was ist ein Curzschluss?",
    # "Was ist ein Kurzschlus?",

### Frage Katalog 2 ###
    # "Wie lauten die fünf Regeln für sicheres Arbeiten an elektrischen Anlagen?",
    # "Welche Berührungsspannung darf bei Menschen maximal auftreten?",
    # "Wofür stehen die Buchstaben T, N und C beim TN-C Netz?",
    # "Wie berechnet man bei einem analogen Messgerät den absoluten sowie den relativen Messfehler?",
    # "Welche Werte braucht man zur Fehlerberechnung bei einem Digitalmessgerät und wie sieht die entsprechende Formel aus?",
    # "Was versteht man unter einem Kurzschluß?",
    # "Wann treten bei einer Tagesbelastungskurve ungefähr Schwachlast, Mittagsspitze und Feierabendspitze auf?",
    # "Was zeichnet ein Grundlastkraftwerk aus?",
    # "Welche beiden Dioden befinden sich in einem Rauch- bzw. Brandmelder?",
    # "Aus welchen drei Teilwiderständen besteht der Widerstand des menschlichen Körpers?",
    # "Von welchen Faktoren hängt die Strombelastbarkeit einer Leitung oder eines Kabels ab?",
    # "Was versteht man unter der Impedanz der Fehlerschleife?",
    # "Welche Bestandteile gehören zum äußeren und welche zum inneren Blitzschutz?",
    # "Welche vier Messfehlerarten werden in den Unterlagen unterschieden?",
    # "Was ist der Unterschied zwichen Kurzschluss, Leiterschluss, Körperschluss und Erdschluss?",
    # "Ein Analogmessgerät besitzt die Klasse 1,5 und einen Endwert von 10 V. Wie hoch darf der absolute Fehler maximal sein?",
    # "Wie verändert sich die erlaubte Abschaltzeit in einem TN-Netz, wenn die Nennwechselspannung ansteigt?",
    # "Welche Bedeutung hat das X bei der Leitungsbezeichnung H05RR-F 3 × 1,5?",
    # "Welche Versorgung ist für eine Synchronmaschine günstiger: Einphasen-Wechselstrom oder Drehstrom?",
    # "Hat ein Feinmessgerät normalerweise einen größeren Anzeigefehler als ein Betriebsmessgerät?",


    ### Frage Kathalog 3 ###
    "Welche drei Arten erneuerbarer Primärenergien werden in der Definition erneuerbarer Energien genannt?",
    "Was ist Biomasse? Nenne 3 Beispiele.",
    "Wie viel Wasserstoff wird pro Sekunde in der Sonne ungefähr in Helium umgewandelt?",
    "Wie hoch ist der Wärmestrom aus dem Erdinneren zur Erdoberfläche ungefähr?",
    "In welchem Jahr wurde der photovoltaische Effekt entdeckt?",
    "Ist die Atmosphäre für solare Strahlung durchlässig?",
    "Welche Strahlungsarten gibt es?",
    "Wie hoch war die weltweit installierte Windleistung bis 2022?",
    "Was sind die Vorteile von Horizontalläufern?",
    "Was sind die Eigenschaften von Laufwasserkraftwerken?",
    "Wie hoch war der Anteil erneuerbarer Energien an der weltweiten Stromerzeugung im Jahr 2023?",
    "Wie groß ist der Speicher von Solarthermie?",
    "Wie hoch ist die Windgeschwindigkeit eines Orkans beziehungsweise bei Orkanstärke?",
    "Wie viel neue Photovoltaikleistung wurde weltweit im Jahr 2023 installiert?",
    "Wie hoch war die maximale Nennleistung einer Windkraftanlage im Jahr 1995?",
    "Wie viel zusätzliche erneuerbare Leistung wurde 2023 in China installiert?",
    "Wie hoch war der Anteil erneuerbarer Energien am deutschen Bruttostromverbrauch im Jahr 2023?",
    "Welche Energiepflanzen gibt es in Mitteleuropa?",
    "Wie hoch war die installierte Windleistung in Deutschland im Jahr 2021?",
    "Wie hoch war 2023 der Anteil erneuerbarer Energien im deutschen Verkehrssektor?",
    "Warum wird Strom aus erneuerbaren Energien in den Unterlagen nicht selbst als regenerativ bezeichnet?",
    "Warum kann Windenergie als indirekte Form der Sonnenenergie betrachtet werden?",
    "Warum erreicht nur ungefähr die Hälfte der außeratmosphärischen Sonnenstrahlung die Erdoberfläche?",
    "Warum ist die Nutzung von Windkraftanlagen offshore besonders effektiv?",
    "Warum muss eine Windkraftanlage bei sehr hohen Windgeschwindigkeiten abgeschaltet werden, obwohl mehr Windenergie vorhanden ist?",
    "Warum eignen sich Pelton-Turbinen besonders für Standorte mit großen Fallhöhen?",
    "Weshalb kann die Verdichtung von Biomasse den Transport wirtschaftlicher machen?",
    "Warum benötigt die anaerobe Biogasgewinnung keine Luftzufuhr?",
    "Warum ist Wasserkraft nicht an jedem beliebigen Standort wirtschaftlich nutzbar, obwohl Wasserkraftwerke hohe Wirkungsgrade erreichen können?",
    "Welcher wesentliche Vorteil der Geothermie besteht gegenüber Wind- und Solarenergie hinsichtlich der Energieverfügbarkeit?",
    "Was lässt sich aus der Energiebilanz der Erde über die Bedeutung der Sonnenenergie im Vergleich zu Erdwärme und Gezeiten ableiten?",
    "Welche Technologie dominiert anhand der Grafik die weltweiten Kapazitätszubauten erneuerbarer Energien im Jahr 2023?",
    "Was zeigt die regionale Verteilung der Kapazitätszubauten 2023 über Chinas Bedeutung für den weltweiten Ausbau erneuerbarer Energien?",
    "Welche Entwicklung zeigt die Grafik zur erneuerbaren Wärmeerzeugung zwischen 2011 und 2021?",
    "Was lässt sich aus der deutschen Stromgrafik 2023 über die Bedeutung der Windenergie innerhalb der erneuerbaren Energien ableiten?",
    "Welche langfristige Entwicklung zeigt die Grafik zur erneuerbaren Stromerzeugung in Deutschland von 2000 bis 2023?",
    "Welcher der drei Sektoren Strom, Wärme und Verkehr ist in Deutschland 2023 am stärksten durch erneuerbare Energien geprägt?",
    "Was zeigt der deutsche Kraftwerksmix 2021 bezüglich Wind und Photovoltaik im Vergleich zu fossilen Einzeltechnologien?",
    "Was lässt sich aus der Darstellung des regenerativen Energieangebotes über die Rolle der Solarenergie für andere erneuerbare Energieformen ableiten?",
    "Warum ist das erschließbare Potenzial einer erneuerbaren Energie kleiner als ihr theoretisches Potenzial?",
    "Welche Energieformen gelten im menschlichen Zeithorizont als praktisch nicht aufbrauchbare ursprüngliche Energiequellen?",
    "Welche maximale spezifische Sonnenleistung kann bei besonders günstiger Situation ungefähr am Boden verfügbar sein?",
    "Welcher physikalische Vorgang ermöglicht es einer Solarzelle, Licht unmittelbar in elektrischen Strom umzuwandeln?",
    "Wie nennt man die Bestrahlung einer horizontalen Fläche, wenn unmittelbares Sonnenlicht und atmosphärisch gestreutes Licht gemeinsam betrachtet werden?",
    "In welchem Geschwindigkeitsbereich liefert eine Windturbine gemäß dem beschriebenen Betriebsmodell elektrische Energie und hat ihre Nennleistung noch nicht zwingend erreicht?",
    "Ab welchem Windtempo wird die Anlage aus Gründen des mechanischen Schutzes außer Betrieb genommen?",
    "Welche zwei hydraulischen Größen entscheiden im Wesentlichen darüber, wie viel Leistung ein Wasserkraftstandort bereitstellen kann?",
    "Welches biologische Verfahren wandelt organisches Material ohne Sauerstoff unter Einsatz von Mikroorganismen um?",
    "Welche unterirdische Wärmegewinnung reicht laut Skript ungefähr 2 bis 3 Kilometer tief und kann Temperaturen von etwa 90 bis 120 Grad Celsius bereitstellen?",
    "Welche Energieform weist im Vergleich zu Sonne und Wind den Vorteil auf, nicht von kurzfristigen Wetteränderungen abhängig zu sein?",

    # Fragen mit absichtlichen Rechtschreibfehlern / umgangssprachlicher Formulierung
    "Was sind die erneubare primär energien?",
    "Wie fiel Watt pro Quadratmeter hat die Sonne oben bei der Erdatmosphäre so im Jahresmittel?",
    "Wann wurde dieser Fotovoltaik-Effekt eigentlich entdeckt und von wem?",
    "Wie hoch ist die Windleistung weltweit bis 2022 in GW ungefähr gewesen?",
    "Ab wie viel Meter pro Sekunde Wind macht ein Windrad gar nichts mehr, weil es zu gefährlich ist?",
    "Warum ist Offshore-Wind besser als an Land, also welche Gründe stehen dazu in den Unterlagen?",
    "Bei Wasserkraft, was sind die zwei Sachen, die bestimmen, wie viel Leistung herauskommt?",
    "Wie hoch ist der Heizwert von Biogas in MJ pro Normkubikmeter ungefähr?",
    "Wie tief geht oberflächennahe Geothermie laut Folie maximal?",
    "Welchen Nachteil kann Geothermie bei Hydraulic Fracturing für die Erde beziehungsweise den Untergrund haben?",

    # Rechenfragen
    "Durch eine Fläche von 50 m² strömt Luft mit einer Geschwindigkeit von 8 m/s. Die Luftdichte beträgt 1,225 kg/m³. Welche Luftmasse dm strömt innerhalb von 10 s durch die Fläche?",
    "Eine Luftströmung mit ρ = 1,225 kg/m³, A = 40 m² und v = 10 m/s wirkt für dt = 5 s. Wie groß ist die kinetische Energie dW der durchströmenden Luftmasse?",
    "Wie viel Prozent der Solarkonstante von 1.370 W/m² entsprechen ungefähr 1.000 W/m² an der Erdoberfläche?",
    "Berechne die im Wind enthaltene Leistung bei einer Luftdichte von 1,225 kg/m³, einer durchströmten Fläche von 100 m² und einer Windgeschwindigkeit von 12 m/s.",
    "Deutschland hatte 2022 etwa 58 GW Windleistung. Bis 2030 sollen es 115 GW sein. Um wie viele GW muss die installierte Leistung steigen?",
    "Wie groß ist die flächenbezogene Leistung des Windes bei ρ = 1,225 kg/m³ und einer Windgeschwindigkeit von 9 m/s?",
    "Vor dem Rotor beträgt die Windgeschwindigkeit 12 m/s, hinter dem Rotor 6 m/s. Berechne die Windgeschwindigkeit in der Rotorebene.",
    "Berechne die theoretisch maximale Rotorleistung für ρ = 1,225 kg/m³, v = 10 m/s und A = 80 m².",
    "Für eine Windkraftanlage gelten v1 = 12 m/s, v2 = 6 m/s, A = 100 m² und ρ = 1,225 kg/m³. Berechne die tatsächliche Rotorleistung.",
    "Berechne die flächenbezogene Windleistung bei v = 5 m/s und bei v = 10 m/s, jeweils mit ρ = 1,225 kg/m³. Um welchen Faktor steigt die Leistung, wenn sich die Windgeschwindigkeit verdoppelt?",
]
