QUESTIONS = [
    "Was sind die fünf Sicherheitsregeln?",
    "Welche Berührungsspannungen sind für Menschen zulässig?",
    "Welche Bedeutung haben die Buchstaben T, N und C in der Kennzeichnung TN-C-System?",
    "Wie werden bei einem analogen Messgerät der absolute und der relative Fehler berechnet?",
    "Welche Größen gehen in die Berechnung des Fehlers eines Digitalmessgeräts ein und wie lautet die Formel?",
    "Was ist ein Kurzschluss?",
    "Zu welchen Tageszeiten treten laut Tagesbelastungskurve Schwachlast, Mittagsspitze und Feierabendspitze auf?",
    "Welche Eigenschaften besitzen Grundlastkraftwerke?",
    "Welche zwei Dioden werden im Rauchmelder oder Brandmelder verwendet?",
    "Aus welchen drei Widerständen setzt sich der Körperwiderstand R_K zusammen?",
    "Welche Einflussgrößen wirken sich auf die Strombelastbarkeit von Kabeln und Leitungen aus?",
    "Was ist die Schleifenimpedanz?",
    "Aus welchen Bestandteilen bestehen der äußere und der innere Blitzschutz?",
    "Welche vier Arten von Messfehlern werden im Skript genannt?",
    "Worin unterscheiden sich Kurzschluss, Leiterschluss, Körperschluss und Erdschluss?",
    "Ein analoges Messgerät hat die Genauigkeitsklasse 1,5 und einen Messbereichsendwert von 10 V. Wie groß ist der maximal zulässige absolute Fehler?",
    "Was passiert mit der zulässigen Abschaltzeit im TN-System, wenn die Nennwechselspannung größer wird?",
    "Wofür steht das X in der Kennzeichnung H05RR-F 3 × 1,5?",
    "Welche Stromart ist für den Betrieb einer Synchronmaschine vorteilhafter: einphasiger Wechselstrom oder Drehstrom?",
    "Ist der Anzeigefehler eines Feinmessgeräts größer als der eines Betriebsmessgeräts?",

    # "Was ist ein Kutzschluss?",
    # "Welche Faktoren beinflusen die Strombelastbarkit von Kabeln und Leitungen?",
    # "Nene die fünf Sicherheitsregln in der richtigen Reihenfolge.",
    # "Was ist ein Curzschluss?",
    # "Was ist ein Kurzschlus?",
]