QUESTIONS = [
    "Was sind die fünf Sicherheitsregeln?",
    "Welche Berührungsspannungen sind für Menschen zulässig?",
    "Welche Bedeutung haben die Buchstaben T, N und C in der Kennzeichnung TN-C-System?",
    "Wie werden bei einem analogen Messgerät der absolute und der relative Fehler berechnet?",
    "Welche Größen gehen in die Berechnung des Fehlers eines Digitalmessgeräts ein und wie lautet die Formel?",
    "Was ist ein Kurzschluss?",
    "Zu welchen Tageszeiten treten laut Tagesbelastungskurve Schwachlast, Mittagsspitze und Feierabendspitze auf?",
    "Welche Eigenschaften besitzen Grundlastkraftwerke?",
    "Welche zwei Dioden werden im Rauchmelder oder Brandmelder verwendet?",
    "Aus welchen drei Widerständen setzt sich der Körperwiderstand R_K zusammen?",
    "Welche Einflussgrößen wirken sich auf die Strombelastbarkeit von Kabeln und Leitungen aus?",
    "Was ist die Schleifenimpedanz?",
    "Aus welchen Bestandteilen bestehen der äußere und der innere Blitzschutz?",
    "Welche vier Arten von Messfehlern werden im Skript genannt?",
    "Worin unterscheiden sich Kurzschluss, Leiterschluss, Körperschluss und Erdschluss?",
    "Ein analoges Messgerät hat die Genauigkeitsklasse 1,5 und einen Messbereichsendwert von 10 V. Wie groß ist der maximal zulässige absolute Fehler?",
    "Was passiert mit der zulässigen Abschaltzeit im TN-System, wenn die Nennwechselspannung größer wird?",
    "Wofür steht das X in der Kennzeichnung H05RR-F 3 × 1,5?",
    "Welche Stromart ist für den Betrieb einer Synchronmaschine vorteilhafter: einphasiger Wechselstrom oder Drehstrom?",
    "Ist der Anzeigefehler eines Feinmessgeräts größer als der eines Betriebsmessgeräts?",

    # "Was ist ein Kutzschluss?",
    # "Welche Faktoren beinflusen die Strombelastbarkit von Kabeln und Leitungen?",
    # "Nene die fünf Sicherheitsregln in der richtigen Reihenfolge.",
    # "Was ist ein Curzschluss?",
    # "Was ist ein Kurzschlus?",


    # "Wie lauten die fünf Regeln für sicheres Arbeiten an elektrischen Anlagen?",
    # "Welche Berührungsspannung darf bei Menschen maximal auftreten?",
    # "Wofür stehen die Buchstaben T, N und C beim TN-C Netz?",
    # "Wie berechnet man bei einem analogen Messgerät den absoluten sowie den relativen Messfehler?",
    # "Welche Werte braucht man zur Fehlerberechnung bei einem Digitalmessgerät und wie sieht die entsprechende Formel aus?",
    # "Was versteht man unter einem Kurzschluß?",
    # "Wann treten bei einer Tagesbelastungskurve ungefähr Schwachlast, Mittagsspitze und Feierabendspitze auf?",
    # "Was zeichnet ein Grundlastkraftwerk aus?",
    # "Welche beiden Dioden befinden sich in einem Rauch- bzw. Brandmelder?",
    # "Aus welchen drei Teilwiderständen besteht der Widerstand des menschlichen Körpers?",
    # "Von welchen Faktoren hängt die Strombelastbarkeit einer Leitung oder eines Kabels ab?",
    # "Was versteht man unter der Impedanz der Fehlerschleife?",
    # "Welche Bestandteile gehören zum äußeren und welche zum inneren Blitzschutz?",
    # "Welche vier Messfehlerarten werden in den Unterlagen unterschieden?",
    # "Was ist der Unterschied zwichen Kurzschluss, Leiterschluss, Körperschluss und Erdschluss?",
    # "Ein Analogmessgerät besitzt die Klasse 1,5 und einen Endwert von 10 V. Wie hoch darf der absolute Fehler maximal sein?",
    # "Wie verändert sich die erlaubte Abschaltzeit in einem TN-Netz, wenn die Nennwechselspannung ansteigt?",
    # "Welche Bedeutung hat das X bei der Leitungsbezeichnung H05RR-F 3 × 1,5?",
    # "Welche Versorgung ist für eine Synchronmaschine günstiger: Einphasen-Wechselstrom oder Drehstrom?",
    # "Hat ein Feinmessgerät normalerweise einen größeren Anzeigefehler als ein Betriebsmessgerät?",
]